# Bot name: Bolt
# Author: orbandit (@just_whiz on Discord)
# Date: 2026-05-01
# Description: A discord bot that reads discord messages and writes to a Google Spreadsheet to log new members of the Garde Imperiale server.
# Version: 0.0.1


# Import essential libraries for the bot's functions
import discord
from discord.ext import commands
import logging
from dotenv import load_dotenv
import os

# Load environment variables from a .env file, which is commonly used to store sensitive information like API tokens. This allows you to keep your Discord token secure and not hard-code it into your script. The load_dotenv() function reads the .env file and makes the variables available in the environment, allowing you to access them using os.getenv().
load_dotenv()
token = os.getenv('DISCORD_TOKEN')

# Set up logging to a file named 'discord.log' with UTF-8 encoding and write mode. This will capture all log messages generated by the bot, which can be useful for debugging and monitoring the bot's activity.
handler = logging.FileHandler(filename='discord.log', encoding='utf-8', mode='w')
intents = discord.Intents.default()
intents.message_content = True
intents.members = True

# Create a new instance of the Bot class with the specified command prefix and intents. The command prefix is set to '!', which means that any message starting with '!' will be treated as a command. The intents specify what events the bot will listen to, such as messages and member updates.
bot = commands.Bot(command_prefix='!', intents=intents)

#This bot event is triggered when the bot successfully connects to Discord and is ready to start receiving events. It prints a message to the console indicating that the bot has logged in, along with the bot's username and ID. This is useful for confirming that the bot is running and connected properly (for debugging purposes)
@bot.event
async def on_ready():
    print(f'Logged in as {bot.user.name} - {bot.user.id}')

#This bot event listens for new members joining the server and sends them a welcome message via direct message. You can customize the welcome message as needed. In this example, it welcomes the new member by name and provides some basic information about the server.
@bot.event
async def on_member_join(member):
    await member.send(f"Welcome to the server {member.name}! We're glad to have you here. If you have any questions, feel free to ask the moderators or check out the rules channel. Enjoy your stay!")

# This bot event listens for messages in the server and responds to them. You can customize the responses based on the content of the message. In this example, it responds to any message that contains "hello" with a greeting that mentions the user who sent the message.
@bot.event
async def on_message(message):
    
    # Prevents the bot from responding to its own messages, which could lead to infinite loops
    if message.author == bot.user: # Checks if the author of the message is the bot itself
        return # returns early from the function, preventing any further code from being executed for this message

    # Handles a simple message response such as a server member saying "hello!"
    if 'hello' in message.content.lower(): # Checks if the message content contains the word "hello" (case-insensitive)
        await message.channel.send(f'Hello {message.author.mention}!') # Sends a greeting by pinging the member who said "hello"

    await bot.process_commands(message) # Allows the bot to continue processing the rest of the commands

bot.run(token, log_handler=handler, log_level=logging.DEBUG) # Starts the bot using the provided token and sets up logging to a file named 'discord.log' with a log level of DEBUG, which will capture detailed information about the bot's activity for troubleshooting and monitoring purposes.